- name: Install neovim
  become: true
  pacman:
    name: neovim
  tags:
    - install
    - neovim

- name: Create required nvim directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload"
    state: directory
    mode: '0755' 
  tags:
    - install
    - neovim
